#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : sof-newlib-xtensa
Version  : 1.x
Release  : 1
URL      : https://github.com/thesofproject/newlib-xtensa/archive/sof-stable-1.x.tar.gz
Source0  : https://github.com/thesofproject/newlib-xtensa/archive/sof-stable-1.x.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-3.0
Requires: sof-newlib-xtensa-license
Requires: sof-newlib-xtensa-data
BuildRequires : bison
BuildRequires : dejagnu
BuildRequires : flex
BuildRequires : sed
BuildRequires : sof-crosstool-ng
BuildRequires : sof-crosstool-ng-dev
BuildRequires : texinfo
Patch1: 0001-support-mockbuild.patch

%description
This directory contains various GNU compilers, assemblers, linkers,
debuggers, etc., plus their support routines, definitions, and documentation.

%package data
Summary: data components for the sof-newlib-xtensa package.
Group: Data

%description data
data components for the sof-newlib-xtensa package.


%package dev
Summary: dev components for the sof-newlib-xtensa package.
Group: Development
Requires: sof-newlib-xtensa-data
Provides: sof-newlib-xtensa-devel

%description dev
dev components for the sof-newlib-xtensa package.


%package license
Summary: license components for the sof-newlib-xtensa package.
Group: Default

%description license
license components for the sof-newlib-xtensa package.


%prep
%setup -q -n newlib-xtensa-sof-stable-1.x
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534753344
pushd mockbuild/
%configure
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534753344
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/sof-newlib-xtensa
cp COPYING3.LIB %{buildroot}/usr/share/doc/sof-newlib-xtensa/COPYING3.LIB
cp COPYING3 %{buildroot}/usr/share/doc/sof-newlib-xtensa/COPYING3
cp COPYING.NEWLIB %{buildroot}/usr/share/doc/sof-newlib-xtensa/COPYING.NEWLIB
cp COPYING.LIB %{buildroot}/usr/share/doc/sof-newlib-xtensa/COPYING.LIB
cp COPYING %{buildroot}/usr/share/doc/sof-newlib-xtensa/COPYING
pushd mockbuild/
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/share/info/configure.info
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/share/info/standards.info
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/lib/crt0.o
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/lib/libc.a
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/lib/libg.a
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/lib/libm.a

%files dev
%defattr(-,root,root,-)
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/_ansi.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/_syslist.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/alloca.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/ar.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/argz.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/assert.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/complex.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/ctype.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/dirent.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/envlock.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/envz.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/errno.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/fastmath.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/fcntl.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/fenv.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/fnmatch.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/getopt.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/glob.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/grp.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/iconv.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/ieeefp.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/inttypes.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/langinfo.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/libgen.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/limits.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/locale.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/_default_types.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/_types.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/ansi.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/endian.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/fastmath.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/ieeefp.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/malloc.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/param.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/setjmp-dj.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/setjmp.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/stdlib.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/termios.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/time.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/machine/types.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/malloc.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/math.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/newlib.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/paths.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/pthread.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/pwd.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/reent.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/regdef.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/regex.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sched.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/search.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/setjmp.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/signal.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/stdint.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/stdio.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/stdio_ext.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/stdlib.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/string.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/strings.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/_default_fcntl.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/_types.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/cdefs.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/config.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/custom_file.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/dir.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/dirent.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/errno.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/fcntl.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/features.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/file.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/iconvnls.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/lock.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/param.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/queue.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/reent.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/resource.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/sched.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/signal.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/stat.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/stdio.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/string.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/syslimits.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/time.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/timeb.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/times.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/types.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/unistd.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/utime.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/sys/wait.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/tar.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/termios.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/tgmath.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/time.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/unctrl.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/unistd.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/utime.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/utmp.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/wchar.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/wctype.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/wordexp.h
/usr/share/xtensa-apl-elf/xtensa-apl-elf/lib/xtensa-apl-elf/include/xtensa/config/core-isa.h

%files license
%defattr(-,root,root,-)
/usr/share/doc/sof-newlib-xtensa/COPYING
/usr/share/doc/sof-newlib-xtensa/COPYING.LIB
/usr/share/doc/sof-newlib-xtensa/COPYING.NEWLIB
/usr/share/doc/sof-newlib-xtensa/COPYING3
/usr/share/doc/sof-newlib-xtensa/COPYING3.LIB
